### ISSUE TITLE
Error: Cannot find module 'src/schemas/index.ts'

### ISSUE THREAD

**Issue by ThomasKuhlmann** [mrjono1/joi-to-typescript#50]
**Describe the bug**
After updating from version 1.10.0 to 1.10.1 you get the following error :

`Running joi-to-typescript...
(node:3844) UnhandledPromiseRejectionWarning: Error: Cannot find module 'src/schemas/index.ts'
Require stack:
- /Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/analyseSchemaFile.js
- /Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/convertFilesInDirectory.js
- /Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/index.js
- /Users/thomaskuhlmann/Projects/app/functions/scripts/types.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/Users/thomaskuhlmann/Projects/app/functions/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.analyseSchemaFile (/Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/analyseSchemaFile.js:20:30)
    at Object.convertFilesInDirectory (/Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/convertFilesInDirectory.js:57:58)
    at Object.convertFromDirectory (/Users/thomaskuhlmann/Projects/app/functions/node_modules/joi-to-typescript/dist/index.js:95:62)
    at types (/Users/thomaskuhlmann/Projects/app/functions/scripts/types.ts:7:24)
    at Object.<anonymous> (/Users/thomaskuhlmann/Projects/app/functions/scripts/types.ts:23:1)
(node:3844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**To Reproduce**
Run:

```
import { convertFromDirectory } from "joi-to-typescript";

const types = async (): Promise<void> => {
  console.log("Running joi-to-typescript...");

  // Configure your settings here
  const result = await convertFromDirectory({
    schemaDirectory: "./src/schemas",
    typeOutputDirectory: "./src/interfaces",
    debug: true,
    defaultToRequired: true,
    indexAllToRoot: true,
  });

  if (result) {
    console.log("Completed joi-to-typescript");
  } else {
    console.log("Failed to run joi-to-typescript");
  }
};

types();
```

with version 1.10.1

Reverting back to the previous version solves the problem

**Comment by mrjono1** [comment]
@ThomasKuhlmann thanks for the bug report, I have reproduced the issue

**Comment by mrjono1** [comment]
I must have created issue as part of immutable settings, the fix is this PR https://github.com/mrjono1/joi-to-typescript/pull/51 I'll work through the release soon

**Comment by mrjono1** [comment]
Thankyou for the bug report, this has now been fixed with version 1.10.3

**Comment by ThomasKuhlmann** [comment]
Thanks for the quick turnaround (love this library btw, it's just a huge timesaver!)

**Comment by mrjono1** [comment]
Thankyou for the kind words 👍
